DELIMITER //
CREATE PROCEDURE PRC_DASHBOARD_RESUMO()
BEGIN
    SELECT 
        C.TYPE AS CATEGORIA, 
        SUM(P.AMOUNT) AS TOTAL_RECEBIDO
    FROM CLIENT C
    JOIN RENTAL R ON C.CLIENT_ID = R.CLIENT_ID
    JOIN PAYMENT P ON R.RENTAL_ID = P.RENTAL_ID
    WHERE P.STATUS = 'PAID'
    GROUP BY C.TYPE;
END //
DELIMITER ;
