Tabela CLIENT
CREATE TABLE POC_CLIENT (
    ID_CLIENT INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(100),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela PET
CREATE TABLE POC_PET (
    ID_PET INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    TYPE VARCHAR(50),
    AGE INT,
    AVAILABLE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela RENTAL (Corrigida as referências)
CREATE TABLE POC_RENTAL (
    ID_RENTAL INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENT INT,
    ID_PET INT,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME,
    PRICE DECIMAL(10, 2),
    STATUS VARCHAR(50),
    FOREIGN KEY (ID_CLIENT) REFERENCES POC_CLIENT(ID_CLIENT), -- Corrigido
    FOREIGN KEY (ID_PET) REFERENCES POC_PET(ID_PET)      -- Corrigido
);

-- Tabela PAYMENT
CREATE TABLE POC_PAYMENT (
    ID_PAYMENT INT AUTO_INCREMENT PRIMARY KEY,
    ID_RENTAL INT,
    PAYMENT_METHOD VARCHAR(50),
    PAYMENT_DATE DATETIME,
    AMOUNT DECIMAL(10, 2),
    STATUS VARCHAR(50),
    FOREIGN KEY (ID_RENTAL) REFERENCES POC_RENTAL(ID_RENTAL)
);

-- Tabela LOG (Corrigida a referência)
CREATE TABLE POC_LOG (
    ID_LOG INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENT INT,
    ID_PET INT,
    TABLE_NAME VARCHAR(50),
    ACTION_NAME VARCHAR(50),
    DESCRIPTION TEXT,
    LOG_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CLIENT) REFERENCES POC_CLIENT(ID_CLIENT), -- Corrigido
    FOREIGN KEY (ID_PET) REFERENCES POC_PET(ID_PET)
      Clientes
INSERT INTO POC_CLIENT (NAME, PHONE, EMAIL) VALUES 
('João Silva', '(11) 98888-7777', 'joao@email.com'),
('Maria Oliveira', '(19) 97777-6666', 'maria@email.com');

--  Pets
INSERT INTO POC_PET (NAME, TYPE, AGE, AVAILABLE) VALUES 
('Rex', 'Cachorro', 3, TRUE),
('Mingau', 'Gato', 2, TRUE),
('Luna', 'Cachorro', 5, TRUE);

--  Aluguel (Rental)

INSERT INTO POC_RENTAL (ID_CLIENT, ID_PET, START_DATE, END_DATE, PRICE, STATUS) VALUES 
(1, 1, '2026-05-01 10:00:00', '2026-05-03 10:00:00', 150.00, 'Finalizado'),
(2, 2, '2026-05-01 11:00:00', '2026-05-03 10:01:00', 250.00, 'Finalizado');

-- Pagamento referente ao Aluguel acima (ID_RENTAL 1)
INSERT INTO POC_PAYMENT (ID_RENTAL, PAYMENT_METHOD, PAYMENT_DATE, AMOUNT, STATUS) VALUES 
(1, 'Cartão de Crédito', '2026-05-01 10:05:00', 150.00, 'Aprovado');

-- Log de sistema
INSERT INTO POC_LOG (ID_CLIENT, TABLE_NAME, ACTION_NAME, DESCRIPTION) VALUES 
(1, 'RENTAL', 'CREATE', 'Início de aluguel do pet Rex pelo cliente João.');

INSERT INTO POC_RENTAL (ID_CLIENT, ID_PET, START_DATE, END_DATE, PRICE, STATUS) VALUES 
(1, 1, '2026-05-01 10:00:00', '2026-05-03 10:00:00', 150.00, 'Finalizado'),
(2, 2, '2026-05-01 11:00:00', '2026-05-03 10:01:00', 250.00, 'Finalizado');

-- FATURAMENTO TOTAL
SELECT SUM(AMOUNT) AS FATURAMENTO_TOTAL
FROM PAYMENT
WHERE STATUS = 'PAID';

-- GASTO POR CLIENTE
SELECT 
    C.NAME AS CLIENTE, 
    C.TYPE AS CATEGORIA,
    SUM(P.AMOUNT) AS TOTAL_GASTO
FROM CLIENT C
JOIN RENTAL R ON C.CLIENT_ID = R.CLIENT_ID
JOIN PAYMENT P ON R.RENTAL_ID = P.RENTAL_ID
WHERE P.STATUS = 'PAID'
GROUP BY C.CLIENT_ID, C.NAME, C.TYPE;

QUAL ANIMAL FOI MAIS ALUGADO?
SELECT 
    P.NAME AS NOME_PET, 
    P.TYPE AS ESPECIE,
    COUNT(R.RENTAL_ID) AS TOTAL_ALUGUEIS
FROM PET P
JOIN RENTAL R ON P.PET_ID = R.PET_ID
GROUP BY P.PET_ID
ORDER BY TOTAL_ALUGUEIS DESC
LIMIT 1;

 QUAIS ALUGUÉIS ESTÃO ATIVOS?
SELECT 
    R.RENTAL_ID, 
    C.NAME AS CLIENTE, 
    P.NAME AS ANIMAL, 
    R.START_DATE, 
    R.END_DATE
FROM RENTAL R
JOIN CLIENT C ON R.CLIENT_ID = C.CLIENT_ID
JOIN PET P ON R.PET_ID = P.PET_ID
WHERE R.STATUS = 'ACTIVE';
