-- FATURAMENTO TOTAL
SELECT SUM(AMOUNT) AS FATURAMENTO_TOTAL
FROM PAYMENT
WHERE STATUS = 'PAID';

-- GASTO POR CLIENTE
SELECT 
    C.NAME AS CLIENTE, 
    C.TYPE AS CATEGORIA,
    SUM(P.AMOUNT) AS TOTAL_GASTO
FROM CLIENT C
JOIN RENTAL R ON C.CLIENT_ID = R.CLIENT_ID
JOIN PAYMENT P ON R.RENTAL_ID = P.RENTAL_ID
WHERE P.STATUS = 'PAID'
GROUP BY C.CLIENT_ID, C.NAME, C.TYPE;

QUAL ANIMAL FOI MAIS ALUGADO?
SELECT 
    P.NAME AS NOME_PET, 
    P.TYPE AS ESPECIE,
    COUNT(R.RENTAL_ID) AS TOTAL_ALUGUEIS
FROM PET P
JOIN RENTAL R ON P.PET_ID = R.PET_ID
GROUP BY P.PET_ID
ORDER BY TOTAL_ALUGUEIS DESC
LIMIT 1;

 QUAIS ALUGUÉIS ESTÃO ATIVOS?
SELECT 
    R.RENTAL_ID, 
    C.NAME AS CLIENTE, 
    P.NAME AS ANIMAL, 
    R.START_DATE, 
    R.END_DATE
FROM RENTAL R
JOIN CLIENT C ON R.CLIENT_ID = C.CLIENT_ID
JOIN PET P ON R.PET_ID = P.PET_ID
WHERE R.STATUS = 'ACTIVE';
